-- MySQL Script generated by MySQL Workbench
-- 01/27/18 12:14:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wasps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wasps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wasps` DEFAULT CHARACTER SET utf8 ;
USE `wasps` ;

-- -----------------------------------------------------
-- Table `wasps`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`User` ;

CREATE TABLE IF NOT EXISTS `wasps`.`User` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `userRole` ENUM('user', 'dispatcher', 'admin') NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`Driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`Driver` ;

CREATE TABLE IF NOT EXISTS `wasps`.`Driver` (
  `driverID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `requestStatus` TINYINT(1) NULL,
  PRIMARY KEY (`driverID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `wasps`.`Appointment` (
  `apptID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `driverID` INT NOT NULL,
  `status` TINYINT(1) NULL,
  `apptStart` DATETIME NULL,
  `apptEnd` DATETIME NULL,
  `apptLocation` VARCHAR(300) NULL,
  `numMiles` DECIMAL(5,3) NULL,
  `totalHours` DECIMAL(3,2) NULL,
  `donation` DECIMAL(10,2) NULL,
  `pickupLocation` VARCHAR(300) NULL,
  `pickupTime` DATETIME NULL,
  `wheelchairVan` TINYINT(1) NULL,
  PRIMARY KEY (`apptID`),
  INDEX `fk_Appointment_Driver1_idx` (`driverID` ASC),
  INDEX `fk_Appointment_User1_idx` (`userID` ASC),
  CONSTRAINT `fk_Appointment_Driver1`
    FOREIGN KEY (`driverID`)
    REFERENCES `wasps`.`Driver` (`driverID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Appointment_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `wasps`.`User` (`userID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`EndUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`EndUser` ;

CREATE TABLE IF NOT EXISTS `wasps`.`EndUser` (
  `endUserID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`endUserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`DriverAvailability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`DriverAvailability` ;

CREATE TABLE IF NOT EXISTS `wasps`.`DriverAvailability` (
  `driverAvailabilityID` INT NOT NULL AUTO_INCREMENT,
  `driverID` INT NOT NULL,
  `availableStart` DATETIME NULL,
  `availableEnd` DATETIME NULL,
  PRIMARY KEY (`driverAvailabilityID`),
  INDEX `fk_Driver_Availability_Driver1_idx` (`driverID` ASC),
  CONSTRAINT `fk_Driver_Availability_Driver1`
    FOREIGN KEY (`driverID`)
    REFERENCES `wasps`.`Driver` (`driverID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`AppointmentUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`AppointmentUsers` ;

CREATE TABLE IF NOT EXISTS `wasps`.`AppointmentUsers` (
  `appointmentUsersID` INT NOT NULL AUTO_INCREMENT,
  `apptID` INT NOT NULL,
  `endUserID` INT NOT NULL,
  PRIMARY KEY (`appointmentUsersID`),
  INDEX `fk_AppointmentUsers_Appointment1_idx` (`apptID` ASC),
  INDEX `fk_AppointmentUsers_EndUser1_idx` (`endUserID` ASC),
  CONSTRAINT `fk_AppointmentUsers_Appointment1`
    FOREIGN KEY (`apptID`)
    REFERENCES `wasps`.`Appointment` (`apptID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AppointmentUsers_EndUser1`
    FOREIGN KEY (`endUserID`)
    REFERENCES `wasps`.`EndUser` (`endUserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
