-- MySQL Script generated by MySQL Workbench
-- Sun Feb  4 12:51:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wasps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wasps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wasps` DEFAULT CHARACTER SET utf8 ;
USE `wasps` ;

-- -----------------------------------------------------
-- Table `wasps`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`User` ;

CREATE TABLE IF NOT EXISTS `wasps`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(100) NOT NULL,
  `userRole` ENUM('driver', 'dispatcher', 'passanger') NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `registered` DATETIME NOT NULL,
  `lastOnline` DATETIME NULL,
  `wantsSMS` TINYINT(1) NULL,
  `wantsEmails` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userID_UNIQUE` (`id` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`Ride`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`Ride` ;

CREATE TABLE IF NOT EXISTS `wasps`.`Ride` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `driverID` INT NOT NULL,
  `apptStart` DATETIME NULL,
  `apptEnd` DATETIME NULL,
  `numMiles` DECIMAL(5,3) NULL,
  `totalMinutes` DECIMAL(3,2) NULL,
  `pickupTime` DATETIME NULL,
  `wheelchairVan` TINYINT(1) NULL,
  `status` ENUM('Unverified', 'Pending', 'Scheduled', 'Complete', 'Canceled') NULL,
  `pickupStreetAddress` VARCHAR(255) NULL,
  `pickupCity` VARCHAR(100) NULL,
  `apptStreetAddress` VARCHAR(255) NULL,
  `apptCity` VARCHAR(100) NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ride_Driver_idx` (`driverID` ASC),
  CONSTRAINT `fk_Ride_Driver`
    FOREIGN KEY (`driverID`)
    REFERENCES `wasps`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ride_User`
    FOREIGN KEY (`userID`)
    REFERENCES `wasps`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`DriverAvailability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`DriverAvailability` ;

CREATE TABLE IF NOT EXISTS `wasps`.`DriverAvailability` (
  `id` INT NOT NULL COMMENT '	',
  `start` TIME NOT NULL,
  `end` TIME NOT NULL,
  `days` SET('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat') NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DriverAvailability_User1_idx` (`userID` ASC),
  CONSTRAINT `fk_DriverAvailability_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `wasps`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`DriverAvailabilityException`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`DriverAvailabilityException` ;

CREATE TABLE IF NOT EXISTS `wasps`.`DriverAvailabilityException` (
  `id` INT NOT NULL COMMENT '	',
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DriverAvailabilityException_User1_idx` (`userID` ASC),
  CONSTRAINT `fk_DriverAvailabilityException_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `wasps`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`VolunteerRequest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`VolunteerRequest` ;

CREATE TABLE IF NOT EXISTS `wasps`.`VolunteerRequest` (
  `id` INT NOT NULL,
  `timestamp` DATETIME NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_VolunteerRequest_User1_idx` (`userID` ASC),
  CONSTRAINT `fk_VolunteerRequest_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `wasps`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`Comments` ;

CREATE TABLE IF NOT EXISTS `wasps`.`Comments` (
  `id` INT NOT NULL,
  `comment` VARCHAR(2048) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `userID` INT NOT NULL,
  `rideID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comments_User1_idx` (`userID` ASC),
  INDEX `fk_Comments_Ride1_idx` (`rideID` ASC),
  CONSTRAINT `fk_Comments_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `wasps`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Ride1`
    FOREIGN KEY (`rideID`)
    REFERENCES `wasps`.`Ride` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`User_has_Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`User_has_Address` ;

CREATE TABLE IF NOT EXISTS `wasps`.`User_has_Address` (
  `userID` INT NOT NULL,
  `Address_id` INT NOT NULL,
  PRIMARY KEY (`userID`, `Address_id`),
  INDEX `fk_User_has_Address_User1_idx` (`userID` ASC),
  CONSTRAINT `fk_User_has_Address_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `wasps`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wasps`.`SentMessagesLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wasps`.`SentMessagesLog` ;

CREATE TABLE IF NOT EXISTS `wasps`.`SentMessagesLog` (
  `id` INT NOT NULL,
  `type` ENUM('phone', 'email') NULL,
  `message` VARCHAR(2048) NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SentMessagesLog_User1_idx` (`userID` ASC),
  CONSTRAINT `fk_SentMessagesLog_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `wasps`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
